#ifndef WSJT_FFI_H
#define WSJT_FFI_H

#pragma once

/* Generated by cbindgen — do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Protocol tag selecting which decoder family this handle drives.
 */
typedef enum WsjtProtocol {
    WSJT_PROTOCOL_FT8 = 0,
    WSJT_PROTOCOL_FT4 = 1,
} WsjtProtocol;

/**
 * Status / error code returned by every fallible `wsjt_*` call.
 *
 * Zero is success. Negative values indicate errors; use
 * [`wsjt_last_error`] for a human-readable description.
 */
typedef enum WsjtStatus {
    WSJT_STATUS_OK = 0,
    WSJT_STATUS_INVALID_ARG = -1,
    WSJT_STATUS_UNKNOWN_PROTOCOL = -2,
    WSJT_STATUS_DECODE_FAILED = -3,
    WSJT_STATUS_INTERNAL = -4,
} WsjtStatus;

/**
 * Opaque decoder handle. Construct with [`wsjt_decoder_new`], release with
 * [`wsjt_decoder_free`].
 */
typedef struct WsjtDecoder {
    uint8_t _priv[0];
} WsjtDecoder;

/**
 * One successfully decoded message.
 */
typedef struct WsjtMessage {
    /**
     * Carrier (tone-0) frequency in Hz.
     */
    float freq_hz;
    /**
     * Time offset in seconds from the protocol's nominal frame start.
     */
    float dt_sec;
    /**
     * WSJT-X compatible SNR in dB (2500 Hz reference bandwidth).
     */
    float snr_db;
    /**
     * Hard-decision errors corrected by BP/OSD.
     */
    uint32_t hard_errors;
    /**
     * Decode pass identifier (matches the Rust `DecodeResult::pass`).
     */
    uint8_t pass;
    /**
     * UTF-8, NUL-terminated message text. Owned by the parent
     * [`WsjtMessageList`]; do not free individually.
     */
    char *text;
} WsjtMessage;

/**
 * List of decoded messages returned from a decode call. Caller should
 * zero-initialise before the call; callee fills `items` / `len`.
 */
typedef struct WsjtMessageList {
    /**
     * Array of `len` `WsjtMessage` values.
     */
    struct WsjtMessage *items;
    /**
     * Number of entries in `items`.
     */
    uintptr_t len;
    /**
     * Internal: total allocation (reserved for future growth).
     */
    uintptr_t _cap;
} WsjtMessageList;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns a pointer to the thread-local last-error string, or NULL if no
 * error has been recorded on this thread. The pointer is valid until the
 * next fallible call on this thread.
 */
const char *wsjt_last_error(void);

/**
 * Construct a new decoder handle bound to `protocol`. Returns NULL on
 * failure (see [`wsjt_last_error`]).
 */
struct WsjtDecoder *wsjt_decoder_new(enum WsjtProtocol protocol);

/**
 * Destroy a decoder handle previously returned by [`wsjt_decoder_new`].
 * Passing NULL is a no-op.
 *
 * # Safety
 *
 * `dec` must be a pointer previously returned by [`wsjt_decoder_new`], or
 * NULL. After this call the pointer is dangling.
 */
void wsjt_decoder_free(struct WsjtDecoder *dec);

/**
 * Free a [`WsjtMessageList`] populated by a decode call. The caller must
 * pass the same list (by pointer) they supplied to the decode call.
 * Passing NULL or an already-freed list is safe.
 *
 * # Safety
 *
 * `list` must point to a [`WsjtMessageList`] written by one of the
 * `wsjt_decode_*` functions, or be NULL. After this call, `items` is NULL
 * and `len` is 0.
 */
void wsjt_message_list_free(struct WsjtMessageList *list);

/**
 * Decode one slot of f32 PCM audio at `sample_rate` Hz (non-12 kHz input
 * is resampled internally). Writes zero-or-more messages into `out`.
 *
 * # Safety
 *
 * - `dec` must be a live [`WsjtDecoder`] handle.
 * - `samples` must point to `n_samples` valid `f32` values.
 * - `out` must point to a writable [`WsjtMessageList`]; caller must pair
 *   with [`wsjt_message_list_free`].
 */
enum WsjtStatus wsjt_decode_f32(const struct WsjtDecoder *dec,
                                const float *samples,
                                uintptr_t n_samples,
                                uint32_t sample_rate,
                                struct WsjtMessageList *out);

/**
 * Decode one slot of 16-bit PCM audio at `sample_rate` Hz.
 *
 * # Safety
 *
 * See [`wsjt_decode_f32`].
 */
enum WsjtStatus wsjt_decode_i16(const struct WsjtDecoder *dec,
                                const int16_t *samples,
                                uintptr_t n_samples,
                                uint32_t sample_rate,
                                struct WsjtMessageList *out);

/**
 * Library version, major.minor.patch packed into a 32-bit integer (8 bits
 * per field). Useful for the consumer to sanity-check ABI compatibility.
 */
uint32_t wsjt_version(void);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* WSJT_FFI_H */
